# Generated by Django 3.2.6 on 2022-02-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=120)),
                ('file', models.FileField(upload_to='upload/%Y/%m/%d/')),
                ('file_type', models.CharField(default='txt', max_length=50)),
                ('file_size', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.CharField(max_length=120)),
                ('files_no', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='topics',
            index=models.Index(fields=['topic_name'], name='FileManager_topic_n_bee8fe_idx'),
        ),
        migrations.AddField(
            model_name='folder',
            name='file',
            field=models.ManyToManyField(related_name='f2f', to='FileManager.FileUpload'),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='file_topic',
            field=models.ManyToManyField(related_name='topics', to='FileManager.Topics'),
        ),
        migrations.AddIndex(
            model_name='fileupload',
            index=models.Index(fields=['file_name'], name='FileManager_file_na_f27940_idx'),
        ),
    ]
